# Generated by Django 3.2.6 on 2021-08-29 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospectos', '0002_prospect_salesman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True)),
                ('details', models.TextField(default='No details')),
                ('ok_date', models.DateField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prospectos.prospect')),
            ],
        ),
    ]
