# Generated by Django 3.2.6 on 2021-08-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
