# Generated by Django 3.2.6 on 2021-08-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_name', models.CharField(max_length=120)),
                ('nss', models.BigIntegerField(unique=True)),
                ('birth_date', models.DateField(blank=True)),
                ('facebook_user', models.CharField(max_length=120)),
                ('phone_number', models.BigIntegerField(blank=True)),
                ('total_amount', models.FloatField(help_text='Contaria con', max_length=20)),
                ('sub_viv', models.FloatField(help_text='Sub vivienda', max_length=20)),
                ('monthly_discount', models.FloatField(help_text='Descuento mensual', max_length=20)),
                ('eco', models.FloatField(help_text='Ecotecnologias', max_length=20)),
                ('call_info', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Awaiting call', 'Awaiting call'), ('Rejected call', 'Rejected call'), ('Pending call', 'Pending call'), ('Not interested', 'Not interested'), ('Approved', 'Approved')], default='Pending call', max_length=40)),
                ('attention', models.CharField(default='Chava', max_length=120)),
                ('prospect_user', models.CharField(choices=[('Alejandro', 'Alejandro'), ('Yusne', 'Yusne'), ('Chava', 'Chava')], help_text='Contacto de', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
