# Generated by Django 3.2.6 on 2021-08-29 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='salesman',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
