# Generated by Django 3.2.6 on 2021-08-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='remarks',
            field=models.TextField(default=''),
        ),
    ]
